do-auth-token: ENC[AES256_GCM,data:47q1MdfCpEhPmGh590R3vPRLCacsyEpZKLeQ08L4dEFnWoWicSTI22IZ4inO120om//AinQHZU+J/SpkBX+9rjFvvhzkjnc=,iv:NXfMaLURlYvDXocY46aPtfsRMC8f8rQSi1pHr3jbOZc=,tag:AgiQ/X7zwdytPHzUEb2j7A==,type:str]
do-auth-token-nintendohomebrew: ENC[AES256_GCM,data:Yd3ohda88LTx5E3DhyPtInB5w9kq6FJ5YLVgupzjW6OcH8OARw/acnwAPQXzr582FMzjsJ8cdDPYoAGFiLctpJAaMXj4ByU=,iv:41WY49badnTzi+A0E1rJ7zAZuLkbQrn5PMYAhoDUV+I=,tag:RdzEh8EmSlahDnHEUe8Btw==,type:str]
ghfilter-webhook-url: ENC[AES256_GCM,data:1fbVfmnptV7ncDSBnhdU+gNy+47rF05IoCMkm2HyxIQBSw+cKBlX2IyFf0rEAnCaQuUKluNhAtpK1AO2nKTotXZ8nUf91JYpPkeSb4b2+3oIhkL/R5HRV5il2bQSsBShyKwz4XyFOjfb7gYrr0oyAK1tUVtb09pbnfET/ipxAe0N6g==,iv:nsY1tb//yZuZrzFBdFx0mcEqLgAS2NwK9Nq6Vay3q20=,tag:y7v1jdtaFTkeHM9l9MdsLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNENTQkUrYUpmVFY5dUtl
            eHgrZFlKMDU2a1daSHZsREJkODhMVlA2V1FVClZDbHJ0bnVyYnVqaFdrMHRSR1dX
            cmI3VzB5VW1Jb1V0MmQvVXpucGpaVHMKLS0tIGd3S2tTdEdSak10N3ZpdDIvRUd6
            RU1PeXl3OGNoeXYraGVqYTN6YW84Y0EKJ9W/ErBIvNb+UxVaXL7XpW2FA2m13QNb
            HCHIRXTSSAwiFgizh5ktnEv/hs0W1jSaWwFKbN99feqfqErNX6kwpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR1JSa2RMZlU1N3U5ZEFC
            ZXVMeXJ5dDJtUHhqTjlSYStGM1VMcnVzYTBZClVBVTI1cHZ6cE1YZ00yTU9wTkJO
            eW9MMForbWZrMVNZZk5ieXJPbXc2N00KLS0tIDlrZ2l4STBHdG92MzFnd0o3Wkps
            djloeklkdWE0R0dJbnBIdHUxQ0l6WW8KSkeQpAkqimD/qxz4vc80H+UMZd1yPJbs
            hvht+ZFCZDOtlprXheT/HyDYdeXYAhY0k3HUTMDAYsFYy3tDXMvYyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMEJNVHh6YkVTaDlXUWk0
            bzVudkkzTFN1ZTJ4YWczaG1tZjh5V2NkSkQ4CkN5NHVlMEQyV1ZoOSsxM3pXb2VX
            MEoxbkNqaEFqRDg4ZEpZNXZBbEpEYVEKLS0tIGpZTGM4aUViOW5PMUpOQTJ6eWNK
            TnorenpraXpldGJoUU9CVGtuVVBudmMKy8ywhIbQ8v8pWoDcTRJNXjkOIWNgQzrL
            eg/+PSB+WMimTTHF5vk8ks2QM58cVpMiJAvwgLofEbEXuf34QxyDJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:06:46Z"
    mac: ENC[AES256_GCM,data:oMjzkVuMkxYZt9L5XTB3NzzacAoKp3iBuqoari2ETGlWgxDkIk6jhdvnCEYue40IltIJL0GhUk+weA5GxavPJFSw/kl2zozmcpw7V94KyeNY4hLrB3WqGaSSnn9wogsS4HqDIWzcWGkkd+x1HdsQGT541PcOrrV/Uasl6SbCPDI=,iv:GQa18jZTVB8TRrqdESfgRJY+Mpax7v5+gGmEbxQKpIc=,tag:Z2x6VZxDAUFZL0LV9UK1mA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
