do-auth-token: ENC[AES256_GCM,data:47q1MdfCpEhPmGh590R3vPRLCacsyEpZKLeQ08L4dEFnWoWicSTI22IZ4inO120om//AinQHZU+J/SpkBX+9rjFvvhzkjnc=,iv:NXfMaLURlYvDXocY46aPtfsRMC8f8rQSi1pHr3jbOZc=,tag:AgiQ/X7zwdytPHzUEb2j7A==,type:str]
do-auth-token-nintendohomebrew: ENC[AES256_GCM,data:Yd3ohda88LTx5E3DhyPtInB5w9kq6FJ5YLVgupzjW6OcH8OARw/acnwAPQXzr582FMzjsJ8cdDPYoAGFiLctpJAaMXj4ByU=,iv:41WY49badnTzi+A0E1rJ7zAZuLkbQrn5PMYAhoDUV+I=,tag:RdzEh8EmSlahDnHEUe8Btw==,type:str]
ghfilter-webhook-url: ENC[AES256_GCM,data:1fbVfmnptV7ncDSBnhdU+gNy+47rF05IoCMkm2HyxIQBSw+cKBlX2IyFf0rEAnCaQuUKluNhAtpK1AO2nKTotXZ8nUf91JYpPkeSb4b2+3oIhkL/R5HRV5il2bQSsBShyKwz4XyFOjfb7gYrr0oyAK1tUVtb09pbnfET/ipxAe0N6g==,iv:nsY1tb//yZuZrzFBdFx0mcEqLgAS2NwK9Nq6Vay3q20=,tag:y7v1jdtaFTkeHM9l9MdsLQ==,type:str]
mediawiki-password: ENC[AES256_GCM,data:Z7rrLwW12hZWUuUOXEr4tGzx,iv:bGgZADQ7WS4XhqfLccvWB+ctSA6w1BiKMw02+65SN5I=,tag:+RU8xu+jsjrnJZHf51TZbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGRBcFVLMkF3S0hZa2pI
            ZnphMWpxMEZFc0tOTnVxdUEwRU5nRVkzQUZJCi9KQVFpQUdkSHYxM1RJVnl2dWdU
            Vzd1ZG01Q2VPa2hSRGNzcnpPTWVZUjgKLS0tIEJNYTlvdDMvcUU2cTJrSHhhd2JT
            L0twQnM2NW11ZVk2bnhRQ2VXUm1IdE0Ky3S+PBbnz7y7HmxYQJVwmUn8NX0dEQ26
            /9jCFnbBQHBhuN4HTp5yvGYCaqifgX2WI5kppMv9mUgbgjVX8HSnYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUzdubi9WWkRVNTlncEEy
            TDFJRkNRWHc0K0hoVWVyaUwzU1JmNFRiZ20wCmpFMGx5S0tNUTNFdlVraEd3Q2Zh
            Nk40WDlNTUFHaWVNMFVIUEMzbDRxSWsKLS0tIG5RNXI1WlNoTm1yZWNrZWg0Nysr
            WUp3aGlPZHRtb2lKK0tXQzhCQ2RBYzAKKnO2WLDPUBqjHzmH44502Ie2qLBFG+Xe
            IzKSBVE0JNXXQMCaIT1ctIQaKDXbjhbiMv8w8ke5imWhTMRa/MV9KA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fngvwa570g6efw2jk9etd2rf7mp2jtk9u6ppsndljwp9c44lkavqn68jgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY0ttVTgzK25keENNaTJN
            bmtPSVJzOVhFNndTS3hwR2JmcUk3djJ3cTBnCnBRazhtMTNER3dzRE15dzZuaTFS
            SVBMb0Fvc3A0REd1QVd4VHFpQ2FCMWsKLS0tIHdUVk9rMFI5ZDN3VGlhUHZWZGE3
            MlJLTTRldFVrOFRsNDNYSjJDMGhzRFkKU888eKqlKRkZSPc/nFz9UQ+4szKz+Gaj
            k4VM0zwf9H4GNOS/fal1OFRD7ENzKWdfatsAFtqbjXecZ5xAlMS38w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fvrfujwwddrd6rw686umhcswtel9vpee05s3xve77fpdx4qh44jqlq5vsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RkM5bnJXU094RDVwWmJw
            alJzUXU4SzFzdkQyL3VvQnRXeVNnVTFLZlQwCkloQ2hxbTJDSTRyTEN6dkp5cWpZ
            T3JTY2FkY1BQMm05WHhYc2hmYWhaOWcKLS0tIEJNSDRhaXM5Z3dYYzd1dTd2YjRS
            REI2MWhHWEEyL1ZoK0lPZWJ3N0I5VjQKbm9x3osULxBdCGyJdvQrRZfrpNkunjC3
            GGbgmEp0v+7CaKl/rH1io0b0za0UHdQ+xEoEqVMAXjNGHcznPXjCcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreERDUEVJVWk4eTM5elE3
            STlZUS93eXQ5ZzZRNXFlcjM0UUsvUG9HVVNJCnFSNlNsOC9JQjl1NzJWaGFmUEEz
            alIrdkE3a2kvRGJLNW5HRlhuakRwOHcKLS0tIEtlRDR4T2drWmx5TDY3aXIraDd2
            a3NCM1JYT010a0FWRzFudUZLeGtoYVEKJ3rAqLSKU1e1pK2JwS6k19xmcWTPP0l+
            brXK+VIy3FCMJYxbNCZ8K3sHnsijssyxm7jGu6Qt0i+JdRdevixqSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-28T01:49:17Z"
    mac: ENC[AES256_GCM,data:AisK9/kfR6Gbtrgk3+9wCmoMcOcJJqZIWEOXLNZQEG6VEiWVI3ag2fH680tDfsWu7Xrs/ifx6APNVKsULAFvoFQQqxIE03y5KNYI5/7ffIAtuaLw3BVaKKYH7cCAL9Ueh+tT+ef5EXSly1O3CFMx6ltE20uf8kspekEjpcb8vWU=,iv:kESv398fwavA60cG4wfEtJ7xtrXWCodpcPTyNai3riE=,tag:nNCvrC4eSt3K4GuSskHJyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
