do-auth-token: ENC[AES256_GCM,data:47q1MdfCpEhPmGh590R3vPRLCacsyEpZKLeQ08L4dEFnWoWicSTI22IZ4inO120om//AinQHZU+J/SpkBX+9rjFvvhzkjnc=,iv:NXfMaLURlYvDXocY46aPtfsRMC8f8rQSi1pHr3jbOZc=,tag:AgiQ/X7zwdytPHzUEb2j7A==,type:str]
do-auth-token-nintendohomebrew: ENC[AES256_GCM,data:Yd3ohda88LTx5E3DhyPtInB5w9kq6FJ5YLVgupzjW6OcH8OARw/acnwAPQXzr582FMzjsJ8cdDPYoAGFiLctpJAaMXj4ByU=,iv:41WY49badnTzi+A0E1rJ7zAZuLkbQrn5PMYAhoDUV+I=,tag:RdzEh8EmSlahDnHEUe8Btw==,type:str]
ghfilter-webhook-url: ENC[AES256_GCM,data:1fbVfmnptV7ncDSBnhdU+gNy+47rF05IoCMkm2HyxIQBSw+cKBlX2IyFf0rEAnCaQuUKluNhAtpK1AO2nKTotXZ8nUf91JYpPkeSb4b2+3oIhkL/R5HRV5il2bQSsBShyKwz4XyFOjfb7gYrr0oyAK1tUVtb09pbnfET/ipxAe0N6g==,iv:nsY1tb//yZuZrzFBdFx0mcEqLgAS2NwK9Nq6Vay3q20=,tag:y7v1jdtaFTkeHM9l9MdsLQ==,type:str]
mediawiki-password: ENC[AES256_GCM,data:hSwOfZ7O0Rk=,iv:uIbYFzubSBffTR5Hv2QC3+mbtBZN4HqjtsGr7H3ca8A=,tag:ASp/r/Rqo3nCVn3Sh9TUXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpakhVMmxYMHBGVEVjZ1Rl
            MXM5eFpnUzZaeVNrZGt5aGlmdmpZclM3UlgwClljTWNQNzhDUy9pMWk3WmladTVC
            em9LSDQrLzhQWkdJSFczMFpNSFMveFUKLS0tIHJWSXlWZmlmNVJzaGV6OXJFUXF0
            RFJrQjMwWCtwNEdmRDNzUjJHL01kQkEKlw7HHqUZypJka0jFHMk1yTaMCJKJO0Cw
            Ska4gVNWksJCCm/D5XTPF2zqJUYT+Ep/t/o509UWbJEval1e4vPbSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRWRPd2RPZEVPNGVIRXVm
            SkZ6UjUxZDhmbERQVXo3RXgwZk41NTd3emhBCmp6YXptK0lNV0RUQmpia1FLQWcz
            cGFvbUZXNGtCOG4vbnFXSkw3UzFHalkKLS0tIDdXV0svV1FGbXRmbm1ML0xLY1pK
            OWhhVjdEaC93KytUN2NuOUlLOENkN0kK/tj1h9DuuNEgCoBg4MKyyuxVPQiNNniw
            VgWliFZDXXi4693mA/uKyO7Q4jLV5IqcxrofLPVUDB2fUyJPZlXBGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fngvwa570g6efw2jk9etd2rf7mp2jtk9u6ppsndljwp9c44lkavqn68jgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Nll5UkxzUkcwbzJXL1lk
            S1grenowclpYN0NNMlhCNHRNNnQycVA1TWp3ClBRa29jTEtJQWJtcmNoMmFXK25y
            QWhEYUtJVUZlRkNwcmh5UjF5SWJ5RlkKLS0tIDhNTUJrdGQwVTZlZ3VzYlBISUFZ
            SGx3VnF0d3dnd3FEQTdqUmdUU0x3THMKeNthgljjhnHidWF3FfdFR0G8KEWSmMHc
            XhQ/hHrjk7RwCIbwBKa1X8d4KAv2WJabxG5LchQSWxnA11ULjIleyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVXhDR1ZvNWZYbjg5U2xC
            dUlEUDgyN3lnOUxLNHRZbkZVbm1XS2NpV1hvClB1UWFMWU9vV3FFTXd2R3hWNmVN
            VzUrUENSU1RzYit4YjNIZzRraHd3Qm8KLS0tIGRFOFJ1ajRLNHh5VjE0YXBlTGE3
            ZTYyOFFrdjNoZHRiNGw4eThkLzdaMTgK/hJxvXBSXtO7YoxQ5yMRAopWb/NDjDM8
            AN4JYKCiwBbsSnMtK91IqNydQvAmt1GlK0rhrbq8992pqY7MYUZjEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T19:36:25Z"
    mac: ENC[AES256_GCM,data:OHz4TBC7ZVJZpC8cRkymHTc9DToai4eOacHr8FKnxqCiD+wmXSIntOsq5WWa5jkUj2CL85yoHW4w5ON/rHCcu73Z29EmZJ8f2m6YeaBclc4Rez0cfKgbuNGxtKMsIlb0SvXaxsCb5F9Cfs94jN7m98MxkdrIUT8ev15C7HICBME=,iv:8nCfhduvNEMelSSDLRHHMzzAAw5wTp5sljENbJPJ/0Q=,tag:LDmnso2UUZ9PkA441zTkHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
