do-auth-token: ENC[AES256_GCM,data:47q1MdfCpEhPmGh590R3vPRLCacsyEpZKLeQ08L4dEFnWoWicSTI22IZ4inO120om//AinQHZU+J/SpkBX+9rjFvvhzkjnc=,iv:NXfMaLURlYvDXocY46aPtfsRMC8f8rQSi1pHr3jbOZc=,tag:AgiQ/X7zwdytPHzUEb2j7A==,type:str]
do-auth-token-nintendohomebrew: ENC[AES256_GCM,data:Yd3ohda88LTx5E3DhyPtInB5w9kq6FJ5YLVgupzjW6OcH8OARw/acnwAPQXzr582FMzjsJ8cdDPYoAGFiLctpJAaMXj4ByU=,iv:41WY49badnTzi+A0E1rJ7zAZuLkbQrn5PMYAhoDUV+I=,tag:RdzEh8EmSlahDnHEUe8Btw==,type:str]
ghfilter-webhook-url: ENC[AES256_GCM,data:1fbVfmnptV7ncDSBnhdU+gNy+47rF05IoCMkm2HyxIQBSw+cKBlX2IyFf0rEAnCaQuUKluNhAtpK1AO2nKTotXZ8nUf91JYpPkeSb4b2+3oIhkL/R5HRV5il2bQSsBShyKwz4XyFOjfb7gYrr0oyAK1tUVtb09pbnfET/ipxAe0N6g==,iv:nsY1tb//yZuZrzFBdFx0mcEqLgAS2NwK9Nq6Vay3q20=,tag:y7v1jdtaFTkeHM9l9MdsLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb3JlaFhqZVVCdjdrbjFk
            Wm1xdWR5TDB6dldxZno1SWtENmhhSWNYeEJNCi9DSzlKQ2FWUzltbUtpazZzTGQ3
            UlcwWHBkNXRBbXdEWEVlWlNZSFg1cXcKLS0tIGpBL1dCOTJQeHYxNFZweWpyQnJz
            am9FUHhGT3cwcGtTMWV4eXN3V0lzRWcKtNZ3rQO47pbO90kW0RFv6UzqX0spDRaI
            rwxwPwZPqYJ8N+ZMamHqi2So/h5V5aWfYlUJWWbUL8dsqHT2j6cNiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaDZVbHludTlHaVZBa0ll
            UHNPTnpDVkRzSXBQd3FFRmMwK290aW9FdlZNCk1vUUZpcFNwNDBxTW1PWHB1Nk1m
            K2Q3ZUE4Y1MwamxUVC9LN21xSDJIdjgKLS0tIHE2YlA5TXI2VThTZGtxSktpL1Ax
            amt2OTVWUnh0d2RvVDJLcUZ4ejVUWEEKHmvKAzLO1WMd5J4renDKFNoFKUtBpNbx
            U3lyx2TYst46zJGKcpLB+egCwAXnbJFT1r0BY78LUxR4teAEnmrbYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:06:46Z"
    mac: ENC[AES256_GCM,data:oMjzkVuMkxYZt9L5XTB3NzzacAoKp3iBuqoari2ETGlWgxDkIk6jhdvnCEYue40IltIJL0GhUk+weA5GxavPJFSw/kl2zozmcpw7V94KyeNY4hLrB3WqGaSSnn9wogsS4HqDIWzcWGkkd+x1HdsQGT541PcOrrV/Uasl6SbCPDI=,iv:GQa18jZTVB8TRrqdESfgRJY+Mpax7v5+gGmEbxQKpIc=,tag:Z2x6VZxDAUFZL0LV9UK1mA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
