nextcloud-admin-pass: ENC[AES256_GCM,data:27X3h6tT3Eh7tjuSOSbkWiV0YvRGgdaiOyEhQ9wWdsnyHU7YMlt+KBNwc07XgWcM4YA=,iv:TfxqCH0wqoyj3ZzzZ8g76R4mtzyLU+abs8NLLRxuI0c=,tag:CuE9ya+Ng13EkLND1yPfuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZkJWa2hYN3V3a0NvOU0v
            OXpEOG9RRGlNSVdoZ09HZzE1d2loSWlCb1d3Cm85ZDloWG4wVmJTbHl3d2Z5MExz
            RHFvdW9mRDlxSktkSCtRUEh0Vloza1UKLS0tIHNzMFhMRnJzbGhzOHhIQVJLUkYv
            THpkakNCamhoZ2o0SW54MTUzVTRwQ00KC7WDnwa+b4lwbi4Ut+Yp+56gKYxfVV5M
            nQ6jRM3b99vVwTZhXWc8cdyzj+Wp2Wo7N7qe9xhybGAGEV2fPloHNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WGV5T3YrM050Qit6V2xh
            N2FLRGhIUEdJcnZ1QjdENXZia3ZITWZFZVJBCm9ndUdZckpZVVZjcVRFUUFROEdI
            RXIvZ09vb0pBYlF1VFVyUHBvNnhIdFUKLS0tIEpUQ2RXMkc2cXErK0RuY1pINkFl
            TTNCRlk5cTJoU3NDWFNOeVlrM0d3bmMKwIuWMTdwvZkPEyXbRh22W4pVbdKuGvOr
            WayB60LPhOaJjAoJMd5aJQJP8OdlFGE701zl1wHbNq9EfwHX6cl1eA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbWRJR3Fya3RMU0pYQmVi
            T01BSmVodVlHdFpZNHZrT0R2QkVCWEx3TXpNClRIUWdwY0dxRlFSSXVCREhleDFF
            eVlvdHpwTmNpaFNhK3IyVUVWb2ltbTAKLS0tIGhIblltN1FtanNYZVZPQ2N5SWkz
            dVdOSHVQWmtXSjdYYXhpTUlCVkRRc2sKlr7gPzTNvxsFz52qw15ORus2iF90iQ7p
            snBcCOHYBJuQ6pj1c3wCZAp2sP+HBBpEEwZtjg/Y5ayWeKe3SCi0mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:17:46Z"
    mac: ENC[AES256_GCM,data:vN3XxszEFYKTta394sADkSBotHIc0VxxOFWCGHVAYo9bLPf9VmmmDWYr2TQ/631UUDMQjgyOGtr1pqv6L+DsEz8T8fzYXTDbOUOEoR/WWrpdgng6td3Ecs2M4MdOCM39MbB07/RCUL09jMg2BHurHJATg8k28996Q8RNvI4Wnbk=,iv:LPIsbQO7e73tavRSbTfRXxQ9ajOZ6Lh9NJdqpBCD+zI=,tag:n8huvTWdoU4ntOeIage3IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
