nextcloud-admin-pass: ENC[AES256_GCM,data:27X3h6tT3Eh7tjuSOSbkWiV0YvRGgdaiOyEhQ9wWdsnyHU7YMlt+KBNwc07XgWcM4YA=,iv:TfxqCH0wqoyj3ZzzZ8g76R4mtzyLU+abs8NLLRxuI0c=,tag:CuE9ya+Ng13EkLND1yPfuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTGRzY3lWWjFDdk54TlJp
            aml4VG5HRWE4eUtTc0p1RGo2aFdSMHZDaUZnCmVoR2doNzhWdmhkKy9uVUkvSkV4
            dlROQUJ1V29yRmJ6UzEwMEg2QUNENjgKLS0tIEhCVmlJbk1hcTdmaXRQZVVRWHVx
            Y0JJbzA1cW44bWdVQUNhaDlCVkdlUVEK+0++8FMfmGpGwY3TO1oU15d1j2HwyLO7
            ecBii4BMW02OVkWMGRSIevA0qkcStcBumbgXlaUU6417PoC/MLghRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYm1SRUZhQzhPRFlkWXFB
            bkhwTEZhTit5MENyNHhJTS9ISFd4NlJIaTJVClRSTThnZ2lnRW91TXhScjFBQ0Rk
            M3FZS2ovemZwVTYyL0VqZGZ4TFpWWlUKLS0tIEZNZmNmZUdpNzM2VzRZK3RPYjFy
            WGIvRzdBQWExL0QxTGd0QVJlamZNR0kKFJj8jmHhPdmJ3MfPktsQFMc/5PNJtALO
            2nOfd3/3RHZ13YpowX99Ao/AcLrQ7CLXH4g94OoT/9L1oQBJm4jnuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fngvwa570g6efw2jk9etd2rf7mp2jtk9u6ppsndljwp9c44lkavqn68jgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYVNEUElFMHRWRnNBaXND
            cEd6OVlzdXJ2MUpmaVlnQWUzUXhkL2o2WlR3Cm1YeGZ2SmdueW9mZmF2bjJNMG4r
            YmduYVg5V0hKeWYzcVdWTjV5VFFCYmcKLS0tIGx1TGxhK2ZCMU1Velk1KzJRaVJZ
            SlFKWnVmdU4vMGhtVnQyWGt4L3JndEkKcJvAS8bYzSnYHjYxHHKppWpKq1/4dzJG
            tJmAAxFSyIahNfDeS72Zts61omULhrv9RmO5C7HHCpUdtIMtfN6EoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fvrfujwwddrd6rw686umhcswtel9vpee05s3xve77fpdx4qh44jqlq5vsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVk5MUVBqdWFLOTV5UHdO
            ZHljOFVSYUtMZkpEL2tTaHNwQXlCTDdPL25BClkvVkE4YnJYVS9wR1VUcUpRVDFr
            cnpSQVZWRkgzOFRzdVpDSSsxbEIxRDgKLS0tIGVJRG5RQ0VHK1B4VXN6YUtFUEd5
            QXJseDBSWlVMRGxzbFBkSjVKQUk5VmcKaK9LbkEJwvOqMMBvRKDIJyKsWhdK/pwR
            t4nOBEAU5dht2sxfnaQ0dK2K1dPldQe7TXVYxnrattkKk9RCow4FmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ya07cln520kx27jq944ezpnr9azgxuhw8tjpzdqs9xa7vekeuppqf9lkh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc3gwYitGRW1CUkV4TWFr
            NmQ0OU5ldjZWUXZUUUF1TXZ2UjZHcUVBdmgwCjBkNUZCOWY0S1ZPYUU1VWVnOVhC
            b2MxblFScUxacTVVQjNCMmhYTmI5ZGsKLS0tIDc0NFVsUXlQWDRtVEhubnNRazlt
            RDlaRGVhZVY0cGkxbTVIYVRpNkxodUUKKflO0iWksD1XGIz4s8n7KHHEDXT6g+fF
            vZ+58dVOcfij4vAtX7QF1FTiKPX9O0AhEcUsrFQuZhJv9Zsr8bY6xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:17:46Z"
    mac: ENC[AES256_GCM,data:vN3XxszEFYKTta394sADkSBotHIc0VxxOFWCGHVAYo9bLPf9VmmmDWYr2TQ/631UUDMQjgyOGtr1pqv6L+DsEz8T8fzYXTDbOUOEoR/WWrpdgng6td3Ecs2M4MdOCM39MbB07/RCUL09jMg2BHurHJATg8k28996Q8RNvI4Wnbk=,iv:LPIsbQO7e73tavRSbTfRXxQ9ajOZ6Lh9NJdqpBCD+zI=,tag:n8huvTWdoU4ntOeIage3IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
