nextcloud-admin-pass: ENC[AES256_GCM,data:27X3h6tT3Eh7tjuSOSbkWiV0YvRGgdaiOyEhQ9wWdsnyHU7YMlt+KBNwc07XgWcM4YA=,iv:TfxqCH0wqoyj3ZzzZ8g76R4mtzyLU+abs8NLLRxuI0c=,tag:CuE9ya+Ng13EkLND1yPfuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaVA1b1lNVWxWM3VBRFY3
            UTBmTXM4WDFNM1EyS1BLU1RzWGQ0WFI4cVZFCmhpOUdqclgvS0VBY2R4SWZpMzJu
            RUVjcXUzZkRobnNNclUwY09yaUlaK28KLS0tIFZvTDdFMU9VVFVlSkMrTVRvcS91
            dU9ZL3hZV2ErNzVsRmhDK0I3REhwb1EKmdaLyQq5quUL6l+ejH0zMGFhdPUKYz6u
            AKYJRx+c1adaqvA0p+gcRGmdMXdxZ/qA7WQkEH1iWjdcGieeF3WaYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2pEUEF4TStkQitHcXNT
            c1RkRGJzeFNEMjQ1UW44aW5JOUZMVnVWbHpBCllPOHZnejlHd0tjRkQwaDl5U0k0
            M05aYjBTOGk2S1JMcDdVYlBmakRCVkkKLS0tIGplUHhIc2ZZdG84bzA2TjFtK253
            TjhpUHFwOGpwWmxvczFXM0JsTzJHeWMKT4nTmt5yFbuiDYBIbXDKcpvgfgTZlFPd
            qCciRjlyjo9w8uGvPNTDJ3odt5bhdhCfD18RfXwCi6zN7eoHqpWqAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fngvwa570g6efw2jk9etd2rf7mp2jtk9u6ppsndljwp9c44lkavqn68jgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcjVjRUloWTZrNWRVS05O
            ZGQ3T01zcS9pTVhlMHhieDdXcUkyYURYL1RJClRnOWYrZnExbk43a3QwcFVoUjlv
            eGVjTlplMDkrR1hySVJrbkNtcjRQYTQKLS0tIEFvZHh1OW5OTTJHd29pZE9ncXZW
            ZVpvbE9FZElOL2lYNThBT0FKSTQrN2MKcWbm84Hp/2GJn/tLbQlyL4WpOax6/2vY
            KCLsYfwqFgW6a4yhC41/W4T3DJuFk8+khd1IvJFJOSs7jvbb8Njp+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bDVyKzhCTDUwT05hR2N0
            RDFKbnFUbmZPaXRYcVlEQVlnbkVBTGhzRmdZCnpVYmRlR1NqU1F5a2FzNnBoTG50
            dS9jZ0t3QnhSTGVrMWh5Q2VMcGVoVG8KLS0tIHdVUyt6bnNFQlBaeDNqTEVVb3l6
            Y0lORmRNck9LSFZvMzRUaThsbVhxRkUKYbwIska9PB76ceZAZfIg+EHlJRXvF9sc
            qkxyyAzJteMEVeEMm4KV6NxCRzKWPNKHmCPmmPIC52mjpc+wjwGCPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:17:46Z"
    mac: ENC[AES256_GCM,data:vN3XxszEFYKTta394sADkSBotHIc0VxxOFWCGHVAYo9bLPf9VmmmDWYr2TQ/631UUDMQjgyOGtr1pqv6L+DsEz8T8fzYXTDbOUOEoR/WWrpdgng6td3Ecs2M4MdOCM39MbB07/RCUL09jMg2BHurHJATg8k28996Q8RNvI4Wnbk=,iv:LPIsbQO7e73tavRSbTfRXxQ9ajOZ6Lh9NJdqpBCD+zI=,tag:n8huvTWdoU4ntOeIage3IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
