nextcloud-admin-pass: ENC[AES256_GCM,data:27X3h6tT3Eh7tjuSOSbkWiV0YvRGgdaiOyEhQ9wWdsnyHU7YMlt+KBNwc07XgWcM4YA=,iv:TfxqCH0wqoyj3ZzzZ8g76R4mtzyLU+abs8NLLRxuI0c=,tag:CuE9ya+Ng13EkLND1yPfuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S2ZieHcwN3RuUXhtNGhG
            dmo4SFVqWUVFMmFLVXpDNkVYMWZoRW5QeFFVCmFEZk1pejR3WFhEZ3Faa1IxMWRT
            QzRXSTc4SjdHUEh3MVgxZG5Ya0lPTU0KLS0tIHMxVlhaS2g1dEdkRXNTd29EYmdL
            RlJMK1BHa1RIbjhUSnRSSGw0RVJFZEEKvQXRKvNtS6ckb8KK5kwFtLlCDqzRNspK
            w3xT0J/whLKUOmRMe2PfkobmaxvG98spMzn2sBWO53SUMjT99FYYxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nqu38lhygvytw63kuvekxvznjj6yvqecy7pddq5p29g05vau0afq03nugm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeldqdG1oSUl0bGM1NDF6
            TTNwdS9reVo1U1g2TngwS1RqWlNtMTAzTEVJCnpPaXREOXlyeHZuOGNXMXl0TjUr
            LzNMVmp2VUpzYlJWS1phUDd5TkxHS3cKLS0tICszQjAyNFBjU0dUQTB2dlREYytn
            akxTS093YU5XTnEvMFUyUmYvN094aGcKWL9XALidUDQ65DDP1u8mLF0nCz2VxIFk
            OEJcPfoLldk4tg4/95VVc3+dc39WLEMz3lAalGCm0zvpItWIywOg8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:17:46Z"
    mac: ENC[AES256_GCM,data:vN3XxszEFYKTta394sADkSBotHIc0VxxOFWCGHVAYo9bLPf9VmmmDWYr2TQ/631UUDMQjgyOGtr1pqv6L+DsEz8T8fzYXTDbOUOEoR/WWrpdgng6td3Ecs2M4MdOCM39MbB07/RCUL09jMg2BHurHJATg8k28996Q8RNvI4Wnbk=,iv:LPIsbQO7e73tavRSbTfRXxQ9ajOZ6Lh9NJdqpBCD+zI=,tag:n8huvTWdoU4ntOeIage3IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
