nextcloud-admin-pass: ENC[AES256_GCM,data:27X3h6tT3Eh7tjuSOSbkWiV0YvRGgdaiOyEhQ9wWdsnyHU7YMlt+KBNwc07XgWcM4YA=,iv:TfxqCH0wqoyj3ZzzZ8g76R4mtzyLU+abs8NLLRxuI0c=,tag:CuE9ya+Ng13EkLND1yPfuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eeu3yzn0ede69f5s65mch8g3a48q9z5km2c0p0sv5we5vd7wxpvqsyeysm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbXZNdzAyNzlVZmx0b2dv
            ajlpZUlqMi81WmVvdzM0UkFMSmVIYUdWS3dVCnZUeGJoTUs0ZFN2WVRaNUMzNDhi
            RFFHam5xbERpUzlOSSt5alpmajFONjgKLS0tIE5nc1daTFVEK1F5dHIvdDR2WEs5
            bk1ZL1A4dE5tejMvd3FrWmFpNE14N0UKF8u5ZbMqlvGzK/b2/D8Jz9D7Bwpi9q82
            NRkA/5XpueTuhlV1mVDKEn8WkoL7R5lN8hSrK80P5ge3/aCTE01OPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y7mcpnhdwr7x4ar3vwuydckvrx3juuejn32lpk4gfvruwv0s997q4cmef8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOL29Fd3hPUU8yWEkrZFFB
            SGFPaEllVmwyT0d0MzZHUUhMTmZxV2JuRzJBCkRXSzJDUGtQbDZtbFhoWU5DNUN2
            SzZlckRKcmN1ayttSVJsZStQT0ZnWVEKLS0tIEN3UDNGN2dMK2lIdHg0WVBRTEFZ
            MUYrYmpDOHJMZmlhQUN2dHNYWDVVdTgKpEYI8w8Qlmacha9P/OJqg6NjlB/pLYoH
            vLtDWUjXhA1jW+kDlDafhzINcCGZrlMvzfBK5281oGdgENinjcJeMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fngvwa570g6efw2jk9etd2rf7mp2jtk9u6ppsndljwp9c44lkavqn68jgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMU1NSHhSM0lRaVpEL05t
            cUNEeXlFd2E3UVJwRWVkVDdhK2I3aWZodDNBCkZvcWZCSm1Ic1FOOXJHRTBsdWFn
            SmxFMG9lUGxYbXIrUnBDbzRSL2lSWDAKLS0tIGQvQmxBNFZ5aFBONmlMNklkd1Jw
            RXdjT0Q2bmpiV2VBRloxYzJYYi9TZ0UKqovxu32aaWO9VyM5j6iehl6YR/kLo6+B
            p9rXSG8SB1ZlHKjiw5L28b2JemuV7okqWW6JJv7hU5ErTIhMAGc8Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ya07cln520kx27jq944ezpnr9azgxuhw8tjpzdqs9xa7vekeuppqf9lkh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZURKYnRYR1hUY1ZDZjBi
            ZkNqR3p1WHdvTnBlZzczRS9Sb1FjYUhOZzFRCjRWL0FIbmpjL3lTMVRxQ2VVZUtk
            NXZDM3JzdDlEVHlBaUE3RUNPQW9WUWMKLS0tIEZ5a1pNaUNlQlhOSEJZOTE5ajU2
            RS83UjVmQ1g2bUJ2cUtmNGdibUtEb3cK131ld4kETFmi9VIerKG9qkhLRsFwAqdO
            1Nc/b+InByAsaeAPtWhbRpG7FPPrDBlpTygZVmWNrmCdUSDgQqm7zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T04:17:46Z"
    mac: ENC[AES256_GCM,data:vN3XxszEFYKTta394sADkSBotHIc0VxxOFWCGHVAYo9bLPf9VmmmDWYr2TQ/631UUDMQjgyOGtr1pqv6L+DsEz8T8fzYXTDbOUOEoR/WWrpdgng6td3Ecs2M4MdOCM39MbB07/RCUL09jMg2BHurHJATg8k28996Q8RNvI4Wnbk=,iv:LPIsbQO7e73tavRSbTfRXxQ9ajOZ6Lh9NJdqpBCD+zI=,tag:n8huvTWdoU4ntOeIage3IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
